GRID_SIZE = 10
SCOUT_START_POSITION = (0,0)
GOAL_POSITION = (9,9)

MAX_STEPS = 200

RADAR_DETECTION_RANGE = 2

STEP_REWARD = -0.25
DETECTION_PENALTY = -10
GOAL_REWARD = +100
DESTRUCTION_PENALTY = -100
INVALID_MOVE_PENALTY = -5
DISTANCE_REWARD_SCALE = 2

# --- Tactical env additions ---
STRIKE_POINT = (1, 8)
TACTICAL_SCOUT_START_POSITION = (7, 7)
TACTICAL_HUNTER_START_POSITION = (8, 8)

ESCORT_RADIUS = 2.5
ESCORT_REWARD = 0.03
ESCORT_DISTANCE_PENALTY = 0.25

SCOUT_DETECTION_PENALTY = 1.0
HUNTER_DETECTION_PENALTY = 2.0

JAM_RANGE = 3.0
JAM_SUPPRESSION_STRENGTH = 0.75
JAM_SUPPRESSION_DURATION = 5
JAM_DECEPTION_DURATION = 5

HUNTER_GOAL_REWARD = 30.0
MISSION_SUCCESS_REWARD = 60.0
UNESCORTED_TARGET_PENALTY = -60.0
FUEL_EXHAUSTED_PENALTY = -40.0
TIME_LIMIT_PENALTY = -40.0
LETHAL_PENALTY = -50.0
HUNTER_LETHAL_PENALTY = -50.0
HUNTER_PROGRESS_REWARD = 5.0
