GRID_SIZE = 10
SCOUT_START_POSITION = (0,0)
GOAL_POSITION = (9,9)

MAX_STEPS = 200

RADAR_DETECTION_RANGE = 2

STEP_REWARD = -1
DETECTION_PENALTY = -10
GOAL_REWARD = +100
DESTRUCTION_PENALTY = -100
INVALID_MOVE_PENALTY = -5
DISTANCE_REWARD_SCALE = 2

# --- Tactical env additions ---
STRIKE_POINT = (1, 8)

JAM_RANGE = 3.0
JAM_SUPPRESSION_STRENGTH = 0.75
JAM_SUPPRESSION_DURATION = 5
JAM_DECEPTION_DURATION = 5

LETHAL_PENALTY = -50.0
HUNTER_GOAL_REWARD = 50.0
