GRID_SIZE = 10
SCOUT_START_POSITION = (0,0)
GOAL_POSITION = (9,9)

MAX_STEPS = 200

RADAR_DETECTION_RANGE = 2

STEP_REWARD = -1
DETECTION_PENALTY = -10
GOAL_REWARD = +100
DESTRUCTION_PENALTY = -100
INVALID_MOVE_PENALTY = -5

